# Use the official Node.js image as the base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies first
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the entire backend directory (excluding files in .dockerignore)
COPY ./ ./

# Expose the port
EXPOSE 5000

# Command to start the application
CMD ["node", "server.js"]
